name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  NODE_VERSION: 16
  JAVA_VERSION: 17

jobs:
  # lint:
  #   name: Lint
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Set up Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #     - run: npm i
  #     - run: npm run lint      
  verify-android:
    name: Verify Android
    runs-on: ubuntu-latest
    # needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Set up Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - run: npm ci
      - run: npm run verify:android

  verify-ios:
    name: Verify iOS
    runs-on: macos-latest
    # needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run verify:ios